[sources]
data_source='.'                         # Use absolute paths
source_type='BV'                        # this will specify the loader that is loaded
files_pattern='*.vhdr'                  # the files to check

[streaming]
stream_name='mock_EEG_stream'
mode='repeat'                           # repeat or once
type='regular'                          # regular or irregular
sampling_freq=100                       # sampling rate to be simulated
stream_type='EEG'
# channel_name=['Cz', 'Pz', 'POz']        # if 'all' stream all channels from source, else provide a list of strings e.g. ['C3', 'Cz', 'C4']
channel_name='all'
