# -- this is the setup which is used while running the module as a docker container
[sources]
data_source='/var/eeg'       
source_type='BV'
files_pattern='*.vhdr'

[streaming]
stream_name='mock_EEG_stream'
mode='repeat'                           # repeat or once
type='regular'                          # regular or irregular
sampling_freq=100                      # sampling rate to be simulated
stream_type='EEG'
channel_name=['Cz', 'Pz', 'POz']                      # if 'all' stream all channels from source, else provide a list of strings e.g. ['C3', 'Cz', 'C4']
